// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cn.shenlusoft.java.lunchorder.domain;

import cn.shenlusoft.java.lunchorder.domain.DishDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DishIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DishIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DishIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: DishIntegrationTest: @Transactional;
    
    @Autowired
    private DishDataOnDemand DishIntegrationTest.dod;
    
    @Test
    public void DishIntegrationTest.testCountDishes() {
        org.junit.Assert.assertNotNull("Data on demand for 'Dish' failed to initialize correctly", dod.getRandomDish());
        long count = cn.shenlusoft.java.lunchorder.domain.Dish.countDishes();
        org.junit.Assert.assertTrue("Counter for 'Dish' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DishIntegrationTest.testFindDish() {
        cn.shenlusoft.java.lunchorder.domain.Dish obj = dod.getRandomDish();
        org.junit.Assert.assertNotNull("Data on demand for 'Dish' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Dish' failed to provide an identifier", id);
        obj = cn.shenlusoft.java.lunchorder.domain.Dish.findDish(id);
        org.junit.Assert.assertNotNull("Find method for 'Dish' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Dish' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DishIntegrationTest.testFindAllDishes() {
        org.junit.Assert.assertNotNull("Data on demand for 'Dish' failed to initialize correctly", dod.getRandomDish());
        long count = cn.shenlusoft.java.lunchorder.domain.Dish.countDishes();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Dish', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<cn.shenlusoft.java.lunchorder.domain.Dish> result = cn.shenlusoft.java.lunchorder.domain.Dish.findAllDishes();
        org.junit.Assert.assertNotNull("Find all method for 'Dish' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Dish' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DishIntegrationTest.testFindDishEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Dish' failed to initialize correctly", dod.getRandomDish());
        long count = cn.shenlusoft.java.lunchorder.domain.Dish.countDishes();
        if (count > 20) count = 20;
        java.util.List<cn.shenlusoft.java.lunchorder.domain.Dish> result = cn.shenlusoft.java.lunchorder.domain.Dish.findDishEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Dish' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Dish' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DishIntegrationTest.testFlush() {
        cn.shenlusoft.java.lunchorder.domain.Dish obj = dod.getRandomDish();
        org.junit.Assert.assertNotNull("Data on demand for 'Dish' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Dish' failed to provide an identifier", id);
        obj = cn.shenlusoft.java.lunchorder.domain.Dish.findDish(id);
        org.junit.Assert.assertNotNull("Find method for 'Dish' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDish(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Dish' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DishIntegrationTest.testMerge() {
        cn.shenlusoft.java.lunchorder.domain.Dish obj = dod.getRandomDish();
        org.junit.Assert.assertNotNull("Data on demand for 'Dish' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Dish' failed to provide an identifier", id);
        obj = cn.shenlusoft.java.lunchorder.domain.Dish.findDish(id);
        boolean modified =  dod.modifyDish(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        cn.shenlusoft.java.lunchorder.domain.Dish merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Dish' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DishIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Dish' failed to initialize correctly", dod.getRandomDish());
        cn.shenlusoft.java.lunchorder.domain.Dish obj = dod.getNewTransientDish(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Dish' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Dish' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Dish' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DishIntegrationTest.testRemove() {
        cn.shenlusoft.java.lunchorder.domain.Dish obj = dod.getRandomDish();
        org.junit.Assert.assertNotNull("Data on demand for 'Dish' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Dish' failed to provide an identifier", id);
        obj = cn.shenlusoft.java.lunchorder.domain.Dish.findDish(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Dish' with identifier '" + id + "'", cn.shenlusoft.java.lunchorder.domain.Dish.findDish(id));
    }
    
}
