// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cn.shenlusoft.java.lunchorder.domain;

import cn.shenlusoft.java.lunchorder.domain.DishOrderDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DishOrderIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DishOrderIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DishOrderIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: DishOrderIntegrationTest: @Transactional;
    
    @Autowired
    private DishOrderDataOnDemand DishOrderIntegrationTest.dod;
    
    @Test
    public void DishOrderIntegrationTest.testCountDishOrders() {
        org.junit.Assert.assertNotNull("Data on demand for 'DishOrder' failed to initialize correctly", dod.getRandomDishOrder());
        long count = cn.shenlusoft.java.lunchorder.domain.DishOrder.countDishOrders();
        org.junit.Assert.assertTrue("Counter for 'DishOrder' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DishOrderIntegrationTest.testFindDishOrder() {
        cn.shenlusoft.java.lunchorder.domain.DishOrder obj = dod.getRandomDishOrder();
        org.junit.Assert.assertNotNull("Data on demand for 'DishOrder' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'DishOrder' failed to provide an identifier", id);
        obj = cn.shenlusoft.java.lunchorder.domain.DishOrder.findDishOrder(id);
        org.junit.Assert.assertNotNull("Find method for 'DishOrder' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'DishOrder' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DishOrderIntegrationTest.testFindAllDishOrders() {
        org.junit.Assert.assertNotNull("Data on demand for 'DishOrder' failed to initialize correctly", dod.getRandomDishOrder());
        long count = cn.shenlusoft.java.lunchorder.domain.DishOrder.countDishOrders();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'DishOrder', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<cn.shenlusoft.java.lunchorder.domain.DishOrder> result = cn.shenlusoft.java.lunchorder.domain.DishOrder.findAllDishOrders();
        org.junit.Assert.assertNotNull("Find all method for 'DishOrder' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'DishOrder' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DishOrderIntegrationTest.testFindDishOrderEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'DishOrder' failed to initialize correctly", dod.getRandomDishOrder());
        long count = cn.shenlusoft.java.lunchorder.domain.DishOrder.countDishOrders();
        if (count > 20) count = 20;
        java.util.List<cn.shenlusoft.java.lunchorder.domain.DishOrder> result = cn.shenlusoft.java.lunchorder.domain.DishOrder.findDishOrderEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'DishOrder' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'DishOrder' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DishOrderIntegrationTest.testFlush() {
        cn.shenlusoft.java.lunchorder.domain.DishOrder obj = dod.getRandomDishOrder();
        org.junit.Assert.assertNotNull("Data on demand for 'DishOrder' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'DishOrder' failed to provide an identifier", id);
        obj = cn.shenlusoft.java.lunchorder.domain.DishOrder.findDishOrder(id);
        org.junit.Assert.assertNotNull("Find method for 'DishOrder' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDishOrder(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'DishOrder' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DishOrderIntegrationTest.testMerge() {
        cn.shenlusoft.java.lunchorder.domain.DishOrder obj = dod.getRandomDishOrder();
        org.junit.Assert.assertNotNull("Data on demand for 'DishOrder' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'DishOrder' failed to provide an identifier", id);
        obj = cn.shenlusoft.java.lunchorder.domain.DishOrder.findDishOrder(id);
        boolean modified =  dod.modifyDishOrder(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        cn.shenlusoft.java.lunchorder.domain.DishOrder merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'DishOrder' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DishOrderIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'DishOrder' failed to initialize correctly", dod.getRandomDishOrder());
        cn.shenlusoft.java.lunchorder.domain.DishOrder obj = dod.getNewTransientDishOrder(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'DishOrder' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'DishOrder' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'DishOrder' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DishOrderIntegrationTest.testRemove() {
        cn.shenlusoft.java.lunchorder.domain.DishOrder obj = dod.getRandomDishOrder();
        org.junit.Assert.assertNotNull("Data on demand for 'DishOrder' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'DishOrder' failed to provide an identifier", id);
        obj = cn.shenlusoft.java.lunchorder.domain.DishOrder.findDishOrder(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'DishOrder' with identifier '" + id + "'", cn.shenlusoft.java.lunchorder.domain.DishOrder.findDishOrder(id));
    }
    
}
