// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cn.shenlusoft.java.lunchorder.domain;

import cn.shenlusoft.java.lunchorder.domain.Dish;
import cn.shenlusoft.java.lunchorder.domain.Restaurent;
import cn.shenlusoft.java.lunchorder.domain.RestaurentDataOnDemand;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect DishDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DishDataOnDemand: @Component;
    
    private Random DishDataOnDemand.rnd = new SecureRandom();
    
    private List<Dish> DishDataOnDemand.data;
    
    @Autowired
    private RestaurentDataOnDemand DishDataOnDemand.restaurentDataOnDemand;
    
    public Dish DishDataOnDemand.getNewTransientDish(int index) {
        Dish obj = new Dish();
        setName(obj, index);
        setPrice(obj, index);
        setRestaurent(obj, index);
        return obj;
    }
    
    public void DishDataOnDemand.setName(Dish obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void DishDataOnDemand.setPrice(Dish obj, int index) {
        double price = new Integer(index).doubleValue();
        obj.setPrice(price);
    }
    
    public void DishDataOnDemand.setRestaurent(Dish obj, int index) {
        Restaurent restaurent = restaurentDataOnDemand.getRandomRestaurent();
        obj.setRestaurent(restaurent);
    }
    
    public Dish DishDataOnDemand.getSpecificDish(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Dish obj = data.get(index);
        return Dish.findDish(obj.getId());
    }
    
    public Dish DishDataOnDemand.getRandomDish() {
        init();
        Dish obj = data.get(rnd.nextInt(data.size()));
        return Dish.findDish(obj.getId());
    }
    
    public boolean DishDataOnDemand.modifyDish(Dish obj) {
        return false;
    }
    
    public void DishDataOnDemand.init() {
        data = Dish.findDishEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Dish' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<cn.shenlusoft.java.lunchorder.domain.Dish>();
        for (int i = 0; i < 10; i++) {
            Dish obj = getNewTransientDish(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
