// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cn.shenlusoft.java.lunchorder.domain;

import cn.shenlusoft.java.lunchorder.domain.RestaurentDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RestaurentIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RestaurentIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RestaurentIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: RestaurentIntegrationTest: @Transactional;
    
    @Autowired
    private RestaurentDataOnDemand RestaurentIntegrationTest.dod;
    
    @Test
    public void RestaurentIntegrationTest.testCountRestaurents() {
        org.junit.Assert.assertNotNull("Data on demand for 'Restaurent' failed to initialize correctly", dod.getRandomRestaurent());
        long count = cn.shenlusoft.java.lunchorder.domain.Restaurent.countRestaurents();
        org.junit.Assert.assertTrue("Counter for 'Restaurent' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RestaurentIntegrationTest.testFindRestaurent() {
        cn.shenlusoft.java.lunchorder.domain.Restaurent obj = dod.getRandomRestaurent();
        org.junit.Assert.assertNotNull("Data on demand for 'Restaurent' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Restaurent' failed to provide an identifier", id);
        obj = cn.shenlusoft.java.lunchorder.domain.Restaurent.findRestaurent(id);
        org.junit.Assert.assertNotNull("Find method for 'Restaurent' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Restaurent' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RestaurentIntegrationTest.testFindAllRestaurents() {
        org.junit.Assert.assertNotNull("Data on demand for 'Restaurent' failed to initialize correctly", dod.getRandomRestaurent());
        long count = cn.shenlusoft.java.lunchorder.domain.Restaurent.countRestaurents();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Restaurent', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<cn.shenlusoft.java.lunchorder.domain.Restaurent> result = cn.shenlusoft.java.lunchorder.domain.Restaurent.findAllRestaurents();
        org.junit.Assert.assertNotNull("Find all method for 'Restaurent' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Restaurent' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RestaurentIntegrationTest.testFindRestaurentEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Restaurent' failed to initialize correctly", dod.getRandomRestaurent());
        long count = cn.shenlusoft.java.lunchorder.domain.Restaurent.countRestaurents();
        if (count > 20) count = 20;
        java.util.List<cn.shenlusoft.java.lunchorder.domain.Restaurent> result = cn.shenlusoft.java.lunchorder.domain.Restaurent.findRestaurentEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Restaurent' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Restaurent' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RestaurentIntegrationTest.testFlush() {
        cn.shenlusoft.java.lunchorder.domain.Restaurent obj = dod.getRandomRestaurent();
        org.junit.Assert.assertNotNull("Data on demand for 'Restaurent' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Restaurent' failed to provide an identifier", id);
        obj = cn.shenlusoft.java.lunchorder.domain.Restaurent.findRestaurent(id);
        org.junit.Assert.assertNotNull("Find method for 'Restaurent' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRestaurent(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Restaurent' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RestaurentIntegrationTest.testMerge() {
        cn.shenlusoft.java.lunchorder.domain.Restaurent obj = dod.getRandomRestaurent();
        org.junit.Assert.assertNotNull("Data on demand for 'Restaurent' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Restaurent' failed to provide an identifier", id);
        obj = cn.shenlusoft.java.lunchorder.domain.Restaurent.findRestaurent(id);
        boolean modified =  dod.modifyRestaurent(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        cn.shenlusoft.java.lunchorder.domain.Restaurent merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Restaurent' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RestaurentIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Restaurent' failed to initialize correctly", dod.getRandomRestaurent());
        cn.shenlusoft.java.lunchorder.domain.Restaurent obj = dod.getNewTransientRestaurent(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Restaurent' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Restaurent' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Restaurent' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RestaurentIntegrationTest.testRemove() {
        cn.shenlusoft.java.lunchorder.domain.Restaurent obj = dod.getRandomRestaurent();
        org.junit.Assert.assertNotNull("Data on demand for 'Restaurent' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Restaurent' failed to provide an identifier", id);
        obj = cn.shenlusoft.java.lunchorder.domain.Restaurent.findRestaurent(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Restaurent' with identifier '" + id + "'", cn.shenlusoft.java.lunchorder.domain.Restaurent.findRestaurent(id));
    }
    
}
