// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cn.shenlusoft.java.lunchorder.domain;

import cn.shenlusoft.java.lunchorder.domain.Restaurent;
import java.lang.Long;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect RestaurentDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RestaurentDataOnDemand: @Component;
    
    private Random RestaurentDataOnDemand.rnd = new SecureRandom();
    
    private List<Restaurent> RestaurentDataOnDemand.data;
    
    public Restaurent RestaurentDataOnDemand.getNewTransientRestaurent(int index) {
        Restaurent obj = new Restaurent();
        setName(obj, index);
        setTelephone(obj, index);
        return obj;
    }
    
    public void RestaurentDataOnDemand.setName(Restaurent obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void RestaurentDataOnDemand.setTelephone(Restaurent obj, int index) {
        Long telephone = new Integer(index).longValue();
        obj.setTelephone(telephone);
    }
    
    public Restaurent RestaurentDataOnDemand.getSpecificRestaurent(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Restaurent obj = data.get(index);
        return Restaurent.findRestaurent(obj.getId());
    }
    
    public Restaurent RestaurentDataOnDemand.getRandomRestaurent() {
        init();
        Restaurent obj = data.get(rnd.nextInt(data.size()));
        return Restaurent.findRestaurent(obj.getId());
    }
    
    public boolean RestaurentDataOnDemand.modifyRestaurent(Restaurent obj) {
        return false;
    }
    
    public void RestaurentDataOnDemand.init() {
        data = Restaurent.findRestaurentEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Restaurent' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<cn.shenlusoft.java.lunchorder.domain.Restaurent>();
        for (int i = 0; i < 10; i++) {
            Restaurent obj = getNewTransientRestaurent(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
